### ISSUE TITLE
如何运行项目呢？ 我运行后一片空白

### ISSUE THREAD

**Issue by glowxq** [pengfeiw/threejs-case#7]
我执行的脚本如下
pnpm i 
pnpm run dev

**Comment by glowxq** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/871d7273-f46b-4e72-aba0-8a1d456daf4e">


如何访问您的demo

**Comment by pengfeiw** [comment]
后面的链接直接打开

**Comment by pengfeiw** [comment]
每个 case 源码在 src/case 文件路径下。

**Comment by glowxq** [comment]
感谢，已经打开学习




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pengfeiw/threejs-case"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月4日(星期三) 下午4:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pengfeiw/threejs-case] 如何运行项目呢？ 我运行后一片空白 (Issue #7)





 
每个 case 源码在 src/case 文件路径下。
